version: '3.9'
services:
  ngrok: 
    image: wernight/ngrok
    container_name: ngrok-jenkins
    command: ngrok http http://192.168.1.141:8081
    # port for ngrok ui
    ports:
      - 4040:4040
    environment: 
      NGROK_AUTH: 1QLHjKxOEARPFzRgZSsAbAmuo45_5EZUh1F4DCv8tP27NzoB9
      NGROK_DEBUG: "true"
  jenkins:
      image: hernanku/jenkins-docker:1.0
      # deploy:
      #   resources:
      #     limits:
      #       # cpus: '1'
      #       memory: 2048M
      #     reservations:
      #       # cpus: '0.25'
      #       memory: 512M
      networks: 
        - ci-cd-network
      privileged: true
      user: root
      restart: unless-stopped
      ports:
        - target: 8080
          published: 8081
          protocol: tcp
          mode: host
      container_name: jenkins
      volumes:
        - /Users/admin/docker-data/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        # - /usr/local/bin/docker:/usr/local/bin/docker
      # environment:
      #   - JAVA_OPTS=-Xms512m -Xmx2g -Djava.awt.headless=true

  # sonarqube:
  #     image: sonarqube:8-community
  #     networks: 
  #       - ci-cd-network
  #     container_name: sonarqube
  #     # depends_on:
  #     #   - sonarqube-db
  #     # links:
  #     #   - sonarqube-db
  #     # environment:
  #     #   SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
  #     #   SONAR_JDBC_USERNAME: sonar
  #     #   SONAR_JDBC_PASSWORD: sonar
  #     volumes:
  #       - /Users/admin/docker-data/sonarqube/data:/opt/sonarqube/data
  #       - /Users/admin/docker-data/sonarqube/extensions:/opt/sonarqube/extensions
  #       - /Users/admin/docker-data/sonarqube/logs:/opt/sonarqube/logs
  #       - /Users/admin/docker-data/sonarqube/temp:/opt/sonarqube/temp
  #     ports:
  #       - "8082:9000"
  #     restart: always

  # sonarqube-db:
  #   image: postgres:12
  #   container_name: sonarqube-db
  #   networks: 
  #     - ci-cd-network
  #   environment:
  #     POSTGRES_PASSWORD: sonar
  #     SONARQUBE_DB_USER: sonar
  #     SONARQUBE_DB_PASSWORD: sonar
  #     SONARQUBE_DB: sonar
  #   volumes:
  #     - /docker-data/sonarqube/db-data:/var/lib/postgresql

  # artifactory-db:
  #   image: postgres:12
  #   container_name: artifactory-db
  #   networks: 
  #     - ci-cd-network
  #   environment:
  #     POSTGRES_PASSWORD: artifactory
  #     ARTIFACTORY_DB_USER: artifactory
  #     ARTIFACTORY_DB_PASSWORD: artifactory
  #     ARTIFACTORY_DB: artifactory
    # volumes:
    #   - /Users/admin/docker-data/artifactory/db-data:/var/lib/postgresql

  # Artifactory service
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    deploy:
      resources:
        limits:
          # cpus: '1'
          memory: 2048M
        reservations:
          # cpus: '0.25'
          memory: 512M
    networks: 
      - ci-cd-network
    container_name: artifactory
    ports:
     - 8087:8081
    volumes:
     - /Users/admin/docker-data/artifactory/data:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
    environment:
    - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  # Tomcat server
  tomcat:
    image: docker.io/bitnami/tomcat:9.0-debian-10
    deploy:
      resources:
        limits:
          # cpus: '1'
          memory: 2048M
        reservations:
          # cpus: '0.25'
          memory: 512M
    networks: 
      - ci-cd-network
    container_name: tomcat-server
    ports:
     - 8080:8080
    volumes:
     - /Users/admin/docker-data/tomcat:/bitnami
    environment:
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
      - TOMCAT_USERNAME=tomcat
      - TOMCAT_PASSWORD=tomcat

# container networking
networks:
  ci-cd-network: 
    name: ci-cd-network


